"""Shared settings for task generation."""

from __future__ import annotations


DEFAULT_TASK_FILE_DIR = "task_file"
DOCKERFILE_MAX_ATTEMPTS = 3
TEST_MAX_ATTEMPTS = 3
INSTRUCTION_REWRITE_MAX_ATTEMPTS = 3
DEFAULT_INSTRUCTION_REWRITE_MODE = "mixed"
DEFAULT_LOSSY_INSTRUCTION_RATIO = 0.25
